# Generated by Django 3.2.25 on 2025-04-05 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
