# Generated by Django 5.1.7 on 2025-03-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency_alter_course_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', "Warrior's Path"), ('standard', "Champion's Edge"), ('premium', "King's Throne")], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='base_price',
        ),
        migrations.AlterUniqueTogether(
            name='courseprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='tier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.coursetier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprice',
            name='tier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.coursetier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='tier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.coursetier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='tier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.coursetier'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='courseprice',
            unique_together={('tier', 'currency')},
        ),
        migrations.RemoveField(
            model_name='courseprice',
            name='course',
        ),
    ]
