# Generated by Django 5.1.7 on 2025-03-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coursetier_remove_course_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetier',
            name='courses',
            field=models.ManyToManyField(related_name='available_tiers', to='core.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_courses', to='core.coursetier'),
        ),
    ]
