# Generated by Django 3.2.25 on 2025-04-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentstatus'),
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='user_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usercourse'),
        ),
    ]
